workflows:
  my-workflow:
    name: Android Workflow
    instance_type: mac_mini
    environment:
      xcode: 12.5
      node: 16.9.0
      npm: latest
      java: 1.8
      cocoapods: 1.10.2

    scripts:
      - name: yarn install
        script: yarn install
      - name: react native
        script: |
          cd android
          chmod +x gradlew 
          cd -
          npx react-native run-android
      - name: Build Android APK
        script: |

          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
